//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalizationPointsOfInterest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalizationPointsOfInterest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///{1}.
        /// </summary>
        internal static string Export_Format {
            get {
                return ResourceManager.GetString("Export_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Comparisons.
        /// </summary>
        internal static string Filename_Compare {
            get {
                return ResourceManager.GetString("Filename_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Concatenations.
        /// </summary>
        internal static string Filename_Concats {
            get {
                return ResourceManager.GetString("Filename_Concats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}_{2}.
        /// </summary>
        internal static string Filename_Construction {
            get {
                return ResourceManager.GetString("Filename_Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Formats.
        /// </summary>
        internal static string Filename_Date {
            get {
                return ResourceManager.GetString("Filename_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Formats.
        /// </summary>
        internal static string Filename_Decimal {
            get {
                return ResourceManager.GetString("Filename_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions Returning Strings.
        /// </summary>
        internal static string Filename_Func {
            get {
                return ResourceManager.GetString("Filename_Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Coded Strings.
        /// </summary>
        internal static string Filename_HardCode {
            get {
                return ResourceManager.GetString("Filename_HardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Files (.resx)|*.resx.
        /// </summary>
        internal static string Filter_Resource {
            get {
                return ResourceManager.GetString("Filter_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Info (File Type : Frequency).
        /// </summary>
        internal static string Label_Analyze_Dir {
            get {
                return ResourceManager.GetString("Label_Analyze_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Info (Project Name : Number of Files).
        /// </summary>
        internal static string Label_Analyze_Sln {
            get {
                return ResourceManager.GetString("Label_Analyze_Sln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Comparisons.
        /// </summary>
        internal static string Label_Compare {
            get {
                return ResourceManager.GetString("Label_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Comparisons: 
        ///{0} total comparisons found in {1} files.
        /// </summary>
        internal static string Label_Compare_Results {
            get {
                return ResourceManager.GetString("Label_Compare_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Concatenations.
        /// </summary>
        internal static string Label_Concat {
            get {
                return ResourceManager.GetString("Label_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Concatenations: 
        ///{0} total concatenations found in {1} files.
        /// </summary>
        internal static string Label_Concat_Results {
            get {
                return ResourceManager.GetString("Label_Concat_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Formats.
        /// </summary>
        internal static string Label_DateFormat {
            get {
                return ResourceManager.GetString("Label_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Formats: 
        ///{0} total date formats found in {1} files.
        /// </summary>
        internal static string Label_DateFormat_Results {
            get {
                return ResourceManager.GetString("Label_DateFormat_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Formats.
        /// </summary>
        internal static string Label_Decimal {
            get {
                return ResourceManager.GetString("Label_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Formats: 
        ///{0} total decimal formats found in {1} files.
        /// </summary>
        internal static string Label_Decimal_Results {
            get {
                return ResourceManager.GetString("Label_Decimal_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nIn directory: {0}.
        /// </summary>
        internal static string Label_Directory {
            get {
                return ResourceManager.GetString("Label_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions Returning Strings.
        /// </summary>
        internal static string Label_Func {
            get {
                return ResourceManager.GetString("Label_Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions Returning Strings: 
        ///{0} total functions returning strings found in {1} files.
        /// </summary>
        internal static string Label_Func_Results {
            get {
                return ResourceManager.GetString("Label_Func_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Coded Strings.
        /// </summary>
        internal static string Label_HardCoded {
            get {
                return ResourceManager.GetString("Label_HardCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Coded Strings: 
        ///{0} total hard coded found in {1} files.
        /// </summary>
        internal static string Label_HardCoded_Results {
            get {
                return ResourceManager.GetString("Label_HardCoded_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled at .
        /// </summary>
        internal static string Label_Percentage_Cancelled {
            get {
                return ResourceManager.GetString("Label_Percentage_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing C# file {0} of {1} in directory 
        ///{2}.
        /// </summary>
        internal static string Label_Processing {
            get {
                return ResourceManager.GetString("Label_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results For Filetype: {0} in Project/Folder: {1}.
        /// </summary>
        internal static string Lbl_OverView_Results {
            get {
                return ResourceManager.GetString("Lbl_OverView_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Analysis Results:.
        /// </summary>
        internal static string ListBox_Dir_Results {
            get {
                return ResourceManager.GetString("ListBox_Dir_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}
        ///.
        /// </summary>
        internal static string ListBox_Items {
            get {
                return ResourceManager.GetString("ListBox_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sln Analysis Results.
        /// </summary>
        internal static string ListBox_Sln_Results {
            get {
                return ResourceManager.GetString("ListBox_Sln_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of files: {0}.
        /// </summary>
        internal static string ListBox_Total {
            get {
                return ResourceManager.GetString("ListBox_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing ... just a moment ....
        /// </summary>
        internal static string ListBox_Working {
            get {
                return ResourceManager.GetString("ListBox_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled!.
        /// </summary>
        internal static string Msg_Cancelled {
            get {
                return ResourceManager.GetString("Msg_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Category by marking the corresponding checkbox!.
        /// </summary>
        internal static string Msg_Checkbox {
            get {
                return ResourceManager.GetString("Msg_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Complete.
        /// </summary>
        internal static string Msg_Complete {
            get {
                return ResourceManager.GetString("Msg_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to ExportText!.
        /// </summary>
        internal static string Msg_ExportWarning {
            get {
                return ResourceManager.GetString("Msg_ExportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the file type(s) you wish to parse!.
        /// </summary>
        internal static string Msg_FileType {
            get {
                return ResourceManager.GetString("Msg_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String comparison is the act of comparing the values of two strings.  Comparisons are based on the sort order of each character, and thus differ between locations and must be addressed for localization.  Selecting this feature displays every instance of comparing strings by searching for use of .NET string-combining functions String.Compare, String.CompareTo, String.Equals, and also the StringComparison Enumerator, which is used to specify culture, case, and sort rules used by the previously mentioned .NET  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Msg_Help_Compare {
            get {
                return ResourceManager.GetString("Msg_Help_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Concatenation is the act of combining multiple strings into one in code.  Selecting this feature displays every instance of combining strings within all C# files by searching for use of .NET string-combining function String.Concat and the use of concatenation operation (+) in combination with double quotes (“”).
        ///
        ///Use the drop down menu and the &quot;Expand/Collapse&quot; button to modify the presentation of the results..
        /// </summary>
        internal static string Msg_Help_Concat {
            get {
                return ResourceManager.GetString("Msg_Help_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1) Select to Parse a Solution File or a Directory
        ///Choosing a Solution will parse the selected filetypes associated with the Solution.  Choosing a Directory will parse all selected filetypes within a directory and its subdirectories.
        ///
        ///Step 2) Choose a filetype to Parse
        ///This program currently supports parsing for C# files (.cs), CSHTML files (.cshtml), and Javascript files (.js).  Different parsing options are available depending on which filetype is chosen
        ///
        ///Step 3) Use the &quot;Browse&quot; button to selec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Msg_Help_Config {
            get {
                return ResourceManager.GetString("Msg_Help_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page features instances of hard-coded date format found in the files.  Date formats vary by region, and thus should not be explicitly formatted in source code.  The pattern searches for two to four consecutive “y” characters followed by a slash / or a dash – character.  For example: “yy-” and “/yyyy” would both produce matches.
        ///
        ///Use the drop down menu and the &quot;Expand/Collapse&quot; button to modify the presentation of the results..
        /// </summary>
        internal static string Msg_Help_Date {
            get {
                return ResourceManager.GetString("Msg_Help_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page features instances of hard coded Decimal Formats found in the files.  Decimal formats vary by region, and thus should not be explicitly formatted in source code.  In C#, numeric formats are hard-coded using the combination of numbers and pound characters to specify how many numbers are to be shown before or after a decimal.  Thus, the Regular Expression pattern searches for one or more pound characters (#) followed by a period (.) or comma (,) and then finally any number 0-9 or another pound chara [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Msg_Help_Decimal {
            get {
                return ResourceManager.GetString("Msg_Help_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page features matches for Functions that return type String.  The Regular Expression used searches for the word “string” as the return type for patterns matching method signatures.  The pattern matching accounts for additional and optional modifiers that may be found in the method signature (i.e. abstract, sealed, static) and creates matches based solely on the return type.
        ///
        ///Use the drop down menu and the &quot;Expand/Collapse&quot; button to modify the presentation of the results..
        /// </summary>
        internal static string Msg_Help_Func {
            get {
                return ResourceManager.GetString("Msg_Help_Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page features instances of strings directly embedded into the code.  As much as possible, strings should not be explicitly placed in code and instead be transferred over to an external Resource file.  The Regular Expression used matches alphabetic characters and spaces enclosed in an open and closed double quote.
        ///
        ///Use the drop down menu and the &quot;Expand/Collapse&quot; button to modify the presentation of the results..
        /// </summary>
        internal static string Msg_Help_HardCoded {
            get {
                return ResourceManager.GetString("Msg_Help_HardCoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Window Displays Information on the Selected Solution File or Directory
        ///
        ///Solution:
        ///Displays the total number of the selected file type within the chosen project file(s).  The information display is done automatically every time a new Solution File or Directory is chosen
        ///
        ///Directory:
        ///Displays the total number of files within the directory and all subdirectories followed by a list of filetypes and their frequency, sorted from most frequent ocurring to the least used.
        /// </summary>
        internal static string Msg_Help_Info {
            get {
                return ResourceManager.GetString("Msg_Help_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section displays the results of the parsing in real time for each parsing category.  The top bar graph in blue displays the number of matches as they occur.  The bottom bar graph in orange displays the number of files the matches occur in.  Clicking on any category will bring you to that particular category&apos;s results page.  In each results page, you can find the following:
        ///
        ///a) The name of the file the matches were found in and how many matches were found in that file
        ///b) The line number in the code w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Msg_Help_Results {
            get {
                return ResourceManager.GetString("Msg_Help_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Input .sln file/directory path.
        /// </summary>
        internal static string Msg_Input_Missing {
            get {
                return ResourceManager.GetString("Msg_Input_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a sample warning message!.
        /// </summary>
        internal static string Msg_Warning {
            get {
                return ResourceManager.GetString("Msg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} case(s) found in {1}
        ///{2}
        ///.
        /// </summary>
        internal static string TextBox_Results_Cases {
            get {
                return ResourceManager.GetString("TextBox_Results_Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Line {0} _____ {1}
        ///.
        /// </summary>
        internal static string TextBox_Results_Line {
            get {
                return ResourceManager.GetString("TextBox_Results_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} case(s) found in {1}.
        /// </summary>
        internal static string Treeview_Results {
            get {
                return ResourceManager.GetString("Treeview_Results", resourceCulture);
            }
        }
    }
}
